spring.application.name=auction-platform

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/auctiondb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create or update the database tables based on our @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Redis configuration for fast, in-memory caching
spring.data.redis.host=localhost
spring.data.redis.port=6379
